# https://taskfile.dev

version: "3"

tasks:
  check:
    desc: Check Python code.
    cmds:
      - ruff check --fix

  format:
    desc: Format Python code.
    cmds:
      - ruff format

  test:
    desc: Run tests
    cmds:
      - pytest

  run:
    desc: Run Python dev server
    cmds:
      - poetry run python main.py

  run:ui:
    desc: Run Vite dev server
    cmds:
      - npm --prefix vocexcel-ui run dev
