name: Release

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: ghcr.io/rdflib/vocexcel
  PYTHON_VERSION: "3.11"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up and use Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Git user
        uses: fregante/setup-git-user@v2

      - name: Get release version
        id: version
        run: echo "VALUE=$(npx --yes semver ${{ github.event.release.tag_name }})" >> "$GITHUB_OUTPUT"

      - name: Update project version
        run: |
          poetry version ${{ steps.version.outputs.VALUE }}
          git add pyproject.toml
          git commit -m "chore: release ${{ steps.version.outputs.VALUE }}"
          git push

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          # Set provenance to false due to issue documented here: https://github.com/docker/build-push-action/issues/778
          provenance: false
          platforms: linux/amd64,linux/arm64
